### ISSUE TITLE
getParameterMetaData and getMetaData are not implemented in DatabendPreparedStatement

### ISSUE THREAD

**Issue by cdmikechen** [datafuselabs/databend-jdbc#114]
In some cases where `PreparedStatement` is required, `ResultSetMetaData` or `ParameterMetaData` related objects are used to process SQL. 
databend-jdbc does not currently implement either of these methods.

```java
    @Override
    public ResultSetMetaData getMetaData()
            throws SQLException {
        return null;
    }

    @Override
    public ParameterMetaData getParameterMetaData()
            throws SQLException {
        return null;
    }
```

**Comment by hantmac** [comment]
@cdmikechen Hi thanks for your reporting. Does this `getMetadata` method help? https://github.com/datafuselabs/databend-jdbc/blob/main/databend-jdbc/src/test/java/com/databend/jdbc/TestDatabendDatabaseMetaData.java#L107
