### ISSUE TITLE
Please release  databend-jdbc-${version}.jar for DBeaver 

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend-jdbc#125]
Please release  databend-jdbc-${version}.jar for DBeaver  
https://docs.databend.com/guides/sql-clients/jdbc/#adding-databend-jdbc-driver-to-dbeaver

**Comment by hantmac** [comment]
Hi @wubx , user can download databend-jdbc-${version}.jar from https://repo1.maven.org/maven2/com/databend/databend-jdbc/0.1.5/

**Comment by hantmac** [comment]
Fixed in https://github.com/datafuselabs/databend-jdbc/pull/128
