### ISSUE TITLE
failed to ping databend server

### ISSUE THREAD

**Issue by zhicwu** [datafuselabs/databend-jdbc#153]
Hello there, I'm unable to connect to databend v1.2.302 using JDBC driver v0.1.8.

* request
  ```
  POST /v1/query HTTP/1.1
  Accept: application/json
  X-DATABEND-QUERY-ID: ***
  User-Agent: Databend JDBC Driver/0.1.8
  Content-Type: application/json; charset=utf-8
  Content-Length: 226
  Host: x.x.x.x:8000
  Connection: Keep-Alive
  Accept-Encoding: gzip
  
  {"sql":"select 1","session_id":null,"pagination":{"wait_time_secs":10,"max_rows_in_buffer":5000000,"max_rows_per_page":10000},"session":{"database":"default","settings":null,"keepServerSessionSecs":30},"stage_attachment":null}
  ```

* response
  ```
  HTTP/1.1 401 Unauthorized
  content-length: 69
  date: Fri, 16 Feb 2024 03:00:54 GMT
  
  {"error":{"code":"401","message":"No authorization header detected"}}
  ```

* stack trace
  ```
  java.io.IOException: failed to ping databend server
	  at com.databend.jdbc.DatabendConnection.executePing(DatabendConnection.java:552)
	  at com.databend.jdbc.DatabendConnection.PingDatabendClientV1(DatabendConnection.java:541)
	  at com.databend.jdbc.NonRegisteringDatabendDriver.connect(NonRegisteringDatabendDriver.java:74)
  ```

To reproduce:
1. start databend server by `docker run --rm -it -p8000:8000 datafuselabs/databend:v1.2.307`
2. connect to `jdbc:databend://<server host>:8000/default` using `root`
  Note: `jdbc:databend://root@<server host>:8000/default` did not work too.

**Comment by hantmac** [comment]
HI @zhicwu, what's the config in the query.toml file? 
Maybe you should modifiy the auth part of quer.toml file like:

```
[[query.users]]
name = “root”
auth_type = “no_password”
```

**Comment by zhicwu** [comment]
Thanks @hantmac. I was using the official docker image which has the configuration you mentioned above.

Just tried again using JDBC driver v0.1.9 and datafuselabs/databend:v1.2.344, still the same issue. However, curl works:
```bash
curl -uroot: --request POST 'localhost:8000/v1/query/' --header 'Content-Type: application/json' --data-raw '{"sql": "SELECT 1"}'
```

As a result, in order to access from JDBC driver, I had to start the container by explictly specifying non-empty `QUERY_DEFAULT_USER` and `QUERY_DEFAULT_PASSWORD`.

**Comment by hantmac** [comment]
> Thanks @hantmac. I was using the official docker image which has the configuration you mentioned above.
> 
> Just tried again using JDBC driver v0.1.9 and datafuselabs/databend:v1.2.344, still the same issue. However, curl works:
> 
> ```shell
> curl -uroot: --request POST 'localhost:8000/v1/query/' --header 'Content-Type: application/json' --data-raw '{"sql": "SELECT 1"}'
> ```
> 
> As a result, in order to access from JDBC driver, I had to start the container by explictly specifying non-empty `QUERY_DEFAULT_USER` and `QUERY_DEFAULT_PASSWORD`.

Would you like to share the jdbc code?

**Comment by zhicwu** [comment]
Sure, you can use docker and below code to reproduce the issue, at least on macbook.

```java
// docker run --rm -it -p8000:8000 datafuselabs/databend:nightly
public static void main(String[] args) throws Exception {
    Properties props = new Properties();
    props.setProperty("user", "root");
    try (Connection conn = DriverManager.getConnection("jdbc:databend://localhost:8000/default");
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("select 1")) {
        System.out.println(rs.next());
    }
}
```

**Comment by wubx** [comment]
https://github.com/datafuselabs/databend-jdbc/pull/173   

Maybe can close this issue.
