### ISSUE TITLE
support speacl char in password 

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend-jdbc#236]
https://github.com/datafuselabs/bendsql/issues/462  

databend-jdbc same as above can't use specal char in password.
 like 'mS%aFRZW*GW' or 'mS!aFRZWGW'

**Comment by hantmac** [comment]
I can't reproduce it in databend-jdbc:
![image](https://github.com/user-attachments/assets/85c6597b-fda0-4611-a6fe-43532b06f868)

The test code is:

```
 public void testCreateWithpassword() throws SQLException {
        Connection conn = createConnection();
        conn.createStatement().execute("create user 'u01' identified by 'mS%aFRZW*GW';");
    }
```
