### ISSUE TITLE
bug:  DatabendDatabaseMetaData.getTables() not returning any rows for the given types with VIEW

### ISSUE THREAD

**Issue by kannaiahuppulagithub** [datafuselabs/databend-jdbc#238]
Hi Team,

public ResultSet getTables(String catalog, String schemaPattern, String tableNamePattern, String[] types) in the class is not implmented for the types VIEW in the class https://github.com/datafuselabs/databend-jdbc/blob/main/databend-jdbc/src/main/java/com/databend/jdbc/DatabendDatabaseMetaData.java

the method is not returning any rows for the given type VIEW , its working for TABLE

Thanks,
Kannaiah

**Comment by hantmac** [comment]
@kannaiahuppulagithub Thanks for reporting. We will check and fix it. It would be great if you would like to make a contribution PR 😄

**Comment by hantmac** [comment]
> What is PR ?
> […](#)
> On Wed, 24 Jul, 2024, 15:37 Jeremy, ***@***.***> wrote: @kannaiahuppulagithub <https://u27439339.ct.sendgrid.net/ls/click?upn=u001.tDb8CKAseI6rJ2pworrQOaCSH-2FdrJzae0wKufHfbGfJf6iBLgpgStTRKjGxmwhDtItFokt-2BpbUu38g6jS4Bjow-3D-3DvW8a_51r8jo3L-2BhAoYVmO4X6H1zM7481dCaHIeQa5dAHquvM8wx-2F2Ialn6UX6RY2f-2BDnEqopiIuxwkzvE-2FUqtTlHWtGVeUL09DPEEXt0ga0Kf3j6SLjmf4TTnqMQJAw-2B3KfeH2eTvrY3zpjlGtwI9hvAyOOS1fI-2BmlpZGpgsn7aKAqAG9m6KEPzAyDGiNJixEN7PbzYfTor2Ar6CIflXwvKHeRXq-2BTCPAhOgdXApisSincfSszIc0hnGXMNTx56wgDsL0w1MXqpPrfys-2FtJFzF50qqw-3D-3D> Thanks for reporting. We will check and fix it. It would be great if you would like to make a contribution PR 😄 — Reply to this email directly, view it on GitHub <https://u27439339.ct.sendgrid.net/ls/click?upn=u001.tDb8CKAseI6rJ2pworrQOXJlpObZ7JlG-2Fgo0uQUyLZbvx-2BboSMHD8ppEMOFuLloH4-2BdMgBTnoSJOz88Gcw0Us8JG7t75Oi2r9FI9h8ch9-2FAWg9TxnpZFDUkp6YOMghol4-p2_51r8jo3L-2BhAoYVmO4X6H1zM7481dCaHIeQa5dAHquvM8wx-2F2Ialn6UX6RY2f-2BDnEqopiIuxwkzvE-2FUqtTlHWtGVeUL09DPEEXt0ga0Kf3j6SLjmf4TTnqMQJAw-2B3KfeH1pF9mWTeKAojFGUluIks9HfORNHukhlYNdo7-2Bc5QbTZT-2Bt2x04zb36BIF-2F7ZzOVj2XkWuPglXvVJQdiKoQci4RcLmmiDKYV2-2F76rzEaYrVyuiWhRoWpqSWaxvD6fpWeDqM3-2B46yX2hGgK7k4w-2BtZ2Q-3D-3D>, or unsubscribe <https://u27439339.ct.sendgrid.net/ls/click?upn=u001.tDb8CKAseI6rJ2pworrQOWeEYMhINtVXg49luKI4qmzdh07iCJyB7VSJvEWhiaYdHClV-2F089RvtNts9RP-2FWfRd8I6qRU-2BNtCJO36ju273zE87bBHTFatCXBTdZgnBezYlXf-2BAuCPv5TEbaQsIwipp69-2BEZdTVzQ1-2BxOt6vQ-2Bswq3HvKiqMLefZDW1s-2B6Zx-2FzJOXFP5GHFrZWcHISTI4yV-2BvFErAS8KfrnikAbi3R18o-3DT-FK_51r8jo3L-2BhAoYVmO4X6H1zM7481dCaHIeQa5dAHquvM8wx-2F2Ialn6UX6RY2f-2BDnEqopiIuxwkzvE-2FUqtTlHWtGVeUL09DPEEXt0ga0Kf3j6SLjmf4TTnqMQJAw-2B3KfeHK5PXeauw9kRq04dlxKfvGsPdYq-2B-2B4i7-2BVQCf-2FO8g-2FxsmDbZgp26XP5equzqjcpv067FfZLHIg3cvKYlwuP2-2Bv-2B7jcSPjnp00i5d4T3qsrd25woeEkgDh0wbAEfAb7sjCMCgKZRlUtwhloCI7tH5FDw-3D-3D> . You are receiving this because you were mentioned.Message ID: ***@***.***>
> -- NOTICE: The information contained in this transmission and any attachments is confidential and is for the use of the intended recipient(s) only. If you have received in error, please notify the sender and delete it. If you are not the intended recipient, you must not use, disclose or distribute this e-mail without the author's prior permission.

Pull Request of github.

**Comment by rad-pat** [comment]
Should be fixed in new version of Databend https://github.com/datafuselabs/databend/issues/16039

**Comment by hantmac** [comment]
> Should be fixed in new version of Databend [datafuselabs/databend#16039](https://github.com/datafuselabs/databend/issues/16039)
Yep. Fixed.
