### ISSUE TITLE
[release] v0.2.9

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend-jdbc#258]
Feat:
1. Add multi-endpoint load balancing support: [doc](https://github.com/datafuselabs/databend-jdbc/blob/main/docs/Connection.md#configure-load-balancing-and-failover), [rfc](https://github.com/datafuselabs/databend-jdbc/issues/250)

**Comment by hantmac** [comment]
Feat:
1. Support geometry type for jdbc https://github.com/datafuselabs/databend-jdbc/pull/241


Fix:
1. fix: uploadStream over 2Gi failed https://github.com/datafuselabs/databend-jdbc/pull/242
2. fix: encode speacial char in password  https://github.com/datafuselabs/databend-jdbc/pull/243
3. fix: Switch flags for support catalog in DDL/DML https://github.com/datafuselabs/databend-jdbc/pull/244
4. fix: double INF value response  https://github.com/datafuselabs/databend-jdbc/pull/246
5. fix: getColumns field https://github.com/datafuselabs/databend-jdbc/pull/256

**Comment by rad-pat** [comment]
@hantmac, should this now be available as 0.2.9?
