### ISSUE TITLE
data_type in DatabaseMetaData need to be int

### ISSUE THREAD

**Issue by cdmikechen** [datafuselabs/databend-jdbc#82]
Currently databend-jdbc returns string type, such as `Int32`:

```java
ResultSet rs = conn.getMetaData().getColumns(this.db, this.schema, this.table, "%")
```

![image](https://github.com/databendcloud/databend-jdbc/assets/12069428/8a107708-5d5d-44ff-af33-6e2fc392cce1)

While in fact the type returned by regular databases (such as MySQL) is int, and the data returned depends on `java.sql.Types`

![image](https://github.com/databendcloud/databend-jdbc/assets/12069428/9b12b8ad-6dde-498e-8f31-ba84d6660d62)

**Comment by hantmac** [comment]
Thanks for your report! `databend-jdbc` return the `DatabendRawType` as `Data_Type` now I will try to fix it.
