### ISSUE TITLE
Fixed DatabaseMetaData getColumns function returned ResultSet field values

### ISSUE THREAD

**Issue by cdmikechen** [datafuselabs/databend-jdbc#84]
A few issues about `DatabaseMetaData` return table columns field values that have been identified so far:
* `DATA_TYPE` need to be int https://github.com/databendcloud/databend-jdbc/issues/82
* `TYPE_NAME` does not need to include precision and scale in the case of decimal (Decimal(10, 2) -> Decimal).
* `COLUMN_SIZE` needs to be expressed as the length of the field, for example, if varchar(100), then `COLUMN_SIZE` needs to be 100.
* `DECIMAL_DIGITS` can generally represent decimal type scale, for example, if decimal(10, 2), then `DECIMAL_DIGITS` needs to be 2.
* `COLUMN_DEF` should be field's default value. After my test, the current value taken from `information_schema.columns` is `column_default`, but the actual default value is now on the `default` field.

The other fields have not been tested yet as I don't use them very often..
If I had the time I feel like I could do a more comprehensive comparison with the jdbc client for mysql or postgres to make sure the relevant field values are returned correctly.

**Comment by hantmac** [comment]
Thanks for your help!
