### ISSUE TITLE
After writing null to a string field with JDBC PreparedStatement, these field value will return "NULL"

### ISSUE THREAD

**Issue by cdmikechen** [datafuselabs/databend-jdbc#88]
Using mysqlclient 

![image](https://github.com/databendcloud/databend-jdbc/assets/12069428/f632e54e-0078-44ea-8f67-77593b39d9d7)

Using dbeaver

![image](https://github.com/databendcloud/databend-jdbc/assets/12069428/21f5f235-f3c5-457f-92fd-ccff53093145)

Using java test

![image](https://github.com/databendcloud/databend-jdbc/assets/12069428/1c4f174a-c08a-4df7-8b0e-d11f08ff6fe7)

**Comment by hantmac** [comment]
@cdmikechen Hi bro, I debugged this problem and found it difficult to solve. Because the response from databend server can't differentiate the object NULL or `"NULL"`, so I close this issue temporarily and if you have a much better method, we can make a talk about it.
